- name: Some app
  hosts: localhost

  roles:
    - role: sansible.rsyslog
      rsyslog:
        app_name: default_app
        builtin_configs:
          # generic handler for text based, unformatted log files
          application_logs:
            enabled: true
            logs:
              - path: "/var/log/app_log.log"
          json_logs:
            enabled: true
            logs:
              - path: "/var/log/app_log_json.log"
                options:
                  type_tag: "application_log"
          nginx_access_logs:
            enabled: true
            logs:
              - path: "/var/log/nginx/application_access.log"
